Repository hmcts/azure-alert-to-slack-function, pull requests merged in 2024-02, with the labels that each got.

#15 DTSPO-14238 - Update app settings
  .funcignore
  .gitignore
  azure-pipelines.yaml
  components/infra/data.tf
  components/infra/function.tf
  components/infra/main.tf
  components/infra/provider.tf
  src/functions/httpTrigger.ts
Labels: ithc/add-or-update, demo/add-or-update, test/add-or-update, prod/add-or-update, sbox/add-or-update, stg/add-or-update

#17 DTSPO-14238 - Add business area to pipeline
  azure-pipelines.yaml
  components/infra/data.tf
  components/infra/function.tf
  components/infra/local.tf
  components/infra/main.tf
Labels: CFT_Sbox/add-or-update, CFT_ITHC/add-or-update, CFT_Stg/add-or-update, CFT_Demo/add-or-update, CFT_Prod/add-or-update, cft_test/destroy, sds_sbox/add-or-update, sds_ithc/add-or-update, sds_demo/add-or-update, sds_test/add-or-update, sds_stg/add-or-update, sds_prod/add-or-update

#18 Adding dev environment for SDS
  azure-pipelines.yaml
  environments/dev/dev.tfvars
Labels: CFT_Sbox/add-or-update, CFT_Test/add-or-update, CFT_ITHC/add-or-update, CFT_Stg/add-or-update, CFT_Demo/add-or-update, CFT_Prod/add-or-update, sds_sbox/add-or-update, sds_ithc/add-or-update, sds_demo/add-or-update, sds_test/add-or-update, sds_stg/add-or-update, sds_prod/add-or-update
